### PR TITLE
docs: Add Supabase Authentication example

### PR DESCRIPTION
**Pull request by wscourge**
Based on [this answer](https://github.com/amannn/next-intl/discussions/422#discussioncomment-6529565) with a little improvements.

### CODE REVIEW

**Comment by amannn** [comment]
This looks great, thank you so much! Is this setup working for you in an app?

**Comment by wscourge** [comment]
It does, yes.

**Comment by amannn** [comment]
Fantastic! 🙌

**Comment by adrenalin1** [comment]
@supabase/auth-helpers-nextjs is deprecated, need examples combined with @supabase/ssr...

**Pull request merged**
