### PR TITLE
docs: defaultTranslationMessages with NextIntlClientProvider

### PR DESCRIPTION
**Pull request by janoschherrmann**
Closes #865

### CODE REVIEW

**Review by amannn — APPROVED** [review]
Many thanks @janoschherrmann! 🙏 

I've rephrased your draft a little bit to match the wording and style of the docs, hope that's ok for you!

**Comment by amannn** [comment]
As completely off-topic: Out of curiosity, I found your online courses. They seem really professional, fantastic work there!

I'm thinking about working on an online course for `next-intl` at some point, do you by chance have some advice for beginners in this area? E.g. which course provider you can recommend, basic advice that helps with structuring, considerations for a recording setup, how/if to combine video content with exercises etc.

In case you can recommend some links I'd be really grateful! 🙂

**Comment by janoschherrmann** [comment]
Hey @amannn, thanks for the feedback on my courses!

If you want, we can have a quick chat and I can give you some recommendations :) 

https://cal.com/janosch/30min?date=2024-02-26&month=2024-02

**Comment by amannn** [comment]
That sounds fantastic, I've just scheduled a chat—thank you so much @janoschherrmann! 🙌

**Pull request merged**
