### PR TITLE
feat: Add auto completion to `timeZone` in the Next 13 RSC branch

### PR DESCRIPTION
**Pull request by A7med3bdulBaset**
The same as #359 but for a different branch

### CODE REVIEW

**Comment by amannn** [comment]
Sorry, I think there's been some misunderstanding. What I meant in https://github.com/amannn/next-intl/pull/359#issuecomment-1613355279 is, that the RSC branch has some further usage of `timeZone` (e.g. [in the `i18n.ts` config file](https://next-intl-docs.vercel.app/docs/configuration#time-zone)). The branch adds new code in the `packages/next-intl` folder that uses the time zone as well—that was what I'm referring to.

We can get your changes from https://github.com/amannn/next-intl/pull/359 into the RSC branch by rebasing, I just quickly did that.

However, I now saw that all the usage of `timeZone` in the branch automatically infer the new `TimeZone` type you've introduced due to shared types, so practically there's in fact nothing to do.

I should have been more precise and should have probably checked before, sorry for the confusion!

Thanks again for your help @A7med3bdulBaset!

**Comment by A7med3bdulBaset** [comment]
> However, I now saw that all the usage of timeZone in the branch automatically infer the new TimeZone type you've introduced due to shared types, so practically there's in fact nothing to do.

That what I noticed.
You can close the PR

**Comment by A7med3bdulBaset** [comment]
Can you take a look at #365

**Comment by amannn** [comment]
Yep, I have it on my list, quite busy with work these days!

**Pull request closed without merging**
